import Navbar from "../../components/navbar/navbar";
import { Table } from "react-bootstrap";

function InstrumentView() {
    return (
        <div>
            <Navbar />
            <Table>
                <thead>
                    <tr>
                        <th>BID</th>
                        <th />
                        <th>ASK</th>
                        <th />
                    </tr>
                    <tr>
                        <th>VOLUME</th>
                        <th>PRICE</th>
                        <th>PRICE</th>
                        <th>VOLUME</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td></td>
                        <td>950</td>
                        <td>950</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>900</td>
                        <td>900</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>850</td>
                        <td>850</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>800</td>
                        <td>800</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>750</td>
                        <td>750</td>
                        <td>1</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>700</td>
                        <td>700</td>
                        <td>1</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>650</td>
                        <td>650</td>
                        <td>1</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>600</td>
                        <td>600</td>
                        <td>1</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>550</td>
                        <td>550</td>
                        <td>1</td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>500</td>
                        <td>500</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>450</td>
                        <td>450</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>400</td>
                        <td>400</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>10</td>
                        <td>350</td>
                        <td>350</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>10</td>
                        <td>300</td>
                        <td>300</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>12</td>
                        <td>250</td>
                        <td>250</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>200</td>
                        <td>200</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>150</td>
                        <td>150</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>100</td>
                        <td>100</td>
                        <td></td>
                    </tr>
                </tbody>
            </Table>
        </div>
    )
}

export default InstrumentView;